# Generated by Django 3.2.4 on 2023-01-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230126_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
