# Generated by Django 3.2.4 on 2023-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_driver_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
