# Generated by Django 3.2.4 on 2023-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_driver_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
