# Generated by Django 3.2.4 on 2023-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='currentVisitedPoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='nextPoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='picked',
            field=models.BooleanField(default=False),
        ),
    ]
